export { default as Header } from './header/Header'
export { default as Category } from './categoryCard/Card'
export { default as FloatingDiv } from './floatingDiv/Float'
export { default as Question } from './question/Question'
export { default as Option } from './option/Option'
export { default as Score } from './score/Score'
export { default as QuizResult } from './quizResult/QuizResult'